### ISSUE TITLE
The header moves strangely when showing/hiding keyboard

### ISSUE THREAD

**Issue by yoonchulkoh** [TimOliver/TORoundedTableView#5]
## Hardware / Software

I'm trying latest TORoundedTableViewExample.
I'm using iOS 10.3.1 simulator.

## Goals

I want to implement a setting screen like iOS.
And I want to enter text in a cell.

## Expected Results

The header and footer do not move even if showing/hiding keyboard.

## Actual Results

![gif](https://user-images.githubusercontent.com/420161/31870670-227abeaa-b7ea-11e7-97f2-8f9d098cb965.gif)

## Steps to Reproduce

Add textField to cell.
And showing/hiding keyboard.

**Comment by TimOliver** [comment]
Thanks for the bug report! Hmmm. I'm not sure what is causing that. It looks like the layout code of the table view is getting caught in the animation block of the keyboard. `layoutSubviews` must be getting called automatically.

I'd have to have a long play with it in order to fix it. I'm not sure if I'll ever have the time.

**Comment by TimOliver** [comment]
Uhh, so I tested this just now, and it doesn't seem to be occurring in iOS 12, or iOS 13. HOPEFULLY some combination of iOS updates has fixed it.

I'm going to close it off. If you see this again, please attach a sample app for me to try. :D
